import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Basic',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='app-component'>
          <div className='header'>
            <p>Next-Practice</p>
            <Nav />
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
